<?php
namespace admin\Util;

use QPHP\core\action\Action;

class ActionMiddleware extends Action
{

    public final function before()
    {
        parent::before(); // TODO: Change the autogenerated stub
    }
}
